export default [
    "Chart.js",
    "NodeJS", 
    "React", 
    "Angular", 
    "VueJS", 
    "Vanilla JavaScript", 
    "jQuery", 
    "D3JS", 
    "ExtJS", 
    "WinJS",
    "Bootstrap",
    "Dojo Widgets",
    "jQWidgets",
    "OpenUI5",
    "Polymer",
    "qooxdoo",
    "Webix",
    "Svelte",
    "Google Closure Library",
    "Joose",
    "JsPHP",
    "Microsoft's Ajax library",
    "MochiKit",
    "PDF.js",
    "Rico",
    "Socket.IO",
    "Spry framework",
    "Underscore.js",
    "Express.js",
    "JavaScriptMVC",
    "Knockout",
    
  ];